# Generated by Django 4.1.3 on 2022-11-16 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0004_remove_item_category_item_categories_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='money_management.account'),
        ),
    ]
