# Generated by Django 4.1.3 on 2022-11-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0005_item_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
