# Generated by Django 4.1.3 on 2022-11-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0006_remove_item_categories_item_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
