# Generated by Django 4.1.3 on 2022-11-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0008_alter_item_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
